name: Node tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.X

      - name: Install dependencies
        run: npm install

      - name: Launch eslint
        run: npm run lint
  test:
    needs: analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.X

      - name: Setup environment
        run: |
          touch .env.test
          echo DB_HOST=${{ secrets.DB_HOST }} >> .env.test
          echo DB_PORT=${{ secrets.DB_PORT }} >> .env.test
          echo DB_USERNAME=${{ secrets.DB_USERNAME }} >> .env.test
          echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env.test
          echo DB_DATABASE=${{ secrets.DB_DATABASE }} >> .env.test
          echo FASTIFY_ADDR=${{ secrets.FASTIFY_ADDR }} >> .env.test
          echo FASTIFY_PORT=${{ secrets.FASTIFY_PORT }} >> .env.test
          echo FASTIFY_LOGGING=${{ secrets.FASTIFY_LOGGING }} >> .env.test

      - name: Start docker containers
        run: docker-compose up -d --build

      - name: Install dependencies
        run: npm install

      - name: Launch tests
        run: npm test